! Project Euler Problem 2
!
! I modeled this after the C++ solution, because it was by far the simplest
!
! Problem:
!
! Each new term in the Fibonacci sequence is generated by adding the previous two
! terms. By starting with 1 and 2, the first 10 terms will be:
!
! 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
!
! By considering the terms in the Fibonacci sequence whose values do not exceed
! four million, find the sum of the even-valued terms.

module Problem0002
    implicit none
contains
    pure integer function p0002() result(answer)
        integer :: a = 1, b = 2, i, tmp
        answer = 0

        do while (b < 4000000)
            answer = answer + b

            do i = 1, 3
                tmp = b
                b = a + b
                a = tmp
            end do
        end do
    end function p0002
end module Problem0002
