/**
 * Project Euler Problem 12
 *
 * Problem:
 *
 * The sequence of triangle numbers is generated by adding the natural numbers. So
 * the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
 * terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 * .. code-block::
 *
 *      1: 1
 *      3: 1,3
 *      6: 1,2,3,6
 *     10: 1,2,5,10
 *     15: 1,3,5,15
 *     21: 1,3,7,21
 *     28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 *
 * @return {number}
 **/
exports.p0012 = function() {
    let num = 0;
    for (let x = 1; ; x++) {
        num += x;
        if ([...factors.properDivisors(num)].length > 500) {
            return num;
        }
    }
    return -1;
};

const factors = require('./lib/factors.js');
