matrix:
  include:
    - language: generic
      python: 3.6
      os: osx
      env: pyver=3.6 pydist=macpython linter=true
#          pydist=macports
#          pydist=homebrew
    - language: node_js
      node_js: "11"
      os: osx
      env: jsver=11 linter=true
    - language: c
      os: osx
      env: linter=true
      script: brew install llvm; ln -s "/usr/local/opt/llvm/bin/clang-tidy" "/usr/local/bin/clang-tidy"; make clint
    - language: node_js
      node_js: "11"
      os: osx
      env: jsver=11
    - language: node_js
      node_js: "10"
      os: osx
      env: jsver=10
    - language: node_js
      node_js: "9"
      os: osx
      env: jsver=9
    - language: node_js
      node_js: "8"
      os: osx
      env: jsver=8
    - language: c
      os: osx
      env: COMPILER_OVERRIDE=clang
      script: brew install clang python3; make ctest
    - language: c
      os: osx
      env: COMPILER_OVERRIDE=gcc GCC_OVERRIDE=gcc-9
      osx_image: xcode10.1
      script: brew install gcc; make ctest
    - language: generic
      python: 3.6
      os: osx
      env: pyver=3.6 pydist=macpython NO_SLOW=true
#          pydist=macports
#          pydist=homebrew
    - language: generic
      python: 3.7
      os: osx
      env: pyver=3.7 pydist=macpython NO_SLOW=true
#          pydist=macports
#          pydist=homebrew
    # - language: generic
    #   python: 3.8
    #   os: osx
    #   env: pyver=3.8 pydist=macpython NO_SLOW=true
#          pydist=macports
#          pydist=homebrew
    - language: generic
      python: pypy3
      os: osx
      env: pyver=pypy3 pydist=homebrew NO_SLOW=true

script:
  - sh ./.scripts/travis_script.sh
