matrix:
  include:
    - language: generic
      python: 3.6
      os: osx
      env: pyver=3.6 pydist=macpython linter=true
#          pydist=macports
#          pydist=homebrew
    - language: generic
      python: 3.6
      os: osx
      env: pyver=3.6 pydist=macpython NO_SLOW=true
#          pydist=macports
#          pydist=homebrew
    - language: generic
      python: 3.7
      os: osx
      env: pyver=3.7 pydist=macpython NO_SLOW=true
#          pydist=macports
#          pydist=homebrew
    - language: generic
      python: 3.8
      os: osx
      env: pyver=3.8 pydist=macpython NO_SLOW=true
#          pydist=macports
#          pydist=homebrew
    - language: generic
      python: pypy3
      os: osx
      env: pyver=pypy3 pydist=homebrew NO_SLOW=true
    - language: node_js
      node_js: "7"
      os: osx
      env: jsver=7
    - language: node_js
      node_js: "6"
      os: osx
      env: jsver=6
    - language: node_js
      node_js: "5"
      os: osx
      env: jsver=5
    - language: node_js
      node_js: "4"
      os: osx
      env: jsver=4
    - language: c
      os: osx
      env: COMPILER_OVERRIDE=clang
      script: brew install clang python3; make ctest
    - language: c
      os: osx
      env: COMPILER_OVERRIDE=gcc
      script: brew install gcc python3; make ctest
    - language: c
      os: osx
      env: COMPILER_OVERRIDE=tcc
      script: brew install tcc python3; make ctest

script:
  - sh ./.scripts/travis_script.sh
