matrix:
  include:
    - language: generic
      python: 3.6
      os: osx
      env: pyver=3.6 pydist=macpython linter=true
#          pydist=macports
#          pydist=homebrew
    - language: node_js
      node_js: "10"
      os: osx
      env: jsver=10 linter=true
    - language: node_js
      node_js: "10"
      os: osx
      env: jsver=10
    - language: node_js
      node_js: "9"
      os: osx
      env: jsver=9
    - language: node_js
      node_js: "8"
      os: osx
      env: jsver=8
    - language: c
      os: osx
      env: COMPILER_OVERRIDE=clang
      script: brew install clang python3; make ctest
    - language: c
      os: osx
      env: COMPILER_OVERRIDE=gcc
      script: brew install gcc python3; make ctest
    - language: generic
      python: 3.6
      os: osx
      env: pyver=3.6 pydist=macpython NO_SLOW=true
#          pydist=macports
#          pydist=homebrew
    - language: generic
      python: 3.7
      os: osx
      env: pyver=3.7 pydist=macpython NO_SLOW=true
#          pydist=macports
#          pydist=homebrew
    # - language: generic
    #   python: 3.8
    #   os: osx
    #   env: pyver=3.8 pydist=macpython NO_SLOW=true
#          pydist=macports
#          pydist=homebrew
    - language: generic
      python: pypy3
      os: osx
      env: pyver=pypy3 pydist=homebrew NO_SLOW=true

script:
  - sh ./.scripts/travis_script.sh
