matrix:
  include:
    - language: generic
      python: 3.6
      os: osx
      env: pyver=3.6 pydist=macpython linter=true
#          pydist=macports
#          pydist=homebrew
    - language: node_js
      node_js: "11"
      os: osx
      env: jsver=11 linter=true
    - language: node_js
      node_js: "11"
      os: osx
      env: jsver=11
    - language: node_js
      node_js: "10"
      os: osx
      env: jsver=10
    - language: node_js
      node_js: "9"
      os: osx
      env: jsver=9
    - language: node_js
      node_js: "8"
      os: osx
      env: jsver=8
    - language: c
      os: osx
      env: COMPILER_OVERRIDE=clang
    - language: c
      os: osx
      env: COMPILER_OVERRIDE=gcc GCC_OVERRIDE=gcc-9
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
          - gcc
          update: true
    - language: generic
      python: 3.6
      os: osx
      env: pyver=3.6 pydist=macpython NO_SLOW=true
#          pydist=macports
#          pydist=homebrew
    - language: generic
      python: 3.7
      os: osx
      env: pyver=3.7 pydist=macpython NO_SLOW=true
#          pydist=macports
#          pydist=homebrew
    - language: generic
      python: 3.8
      os: osx
      env: pyver=3.8 pydist=macpython NO_SLOW=true
#          pydist=macports
#          pydist=homebrew
    - language: generic
      python: pypy3
      os: osx
      env: pyver=pypy3 pydist=homebrew NO_SLOW=true
      addons:
        homebrew:
          packages:
          - pypy3
          update: true
    - language: generic
      python: 3.7
      os: osx
      env: pyver=3.7 pydist=macpython ONLY_SLOW=true
  allow_failures:
    - env: ONLY_SLOW=true
    - python: pypy3

script:
  - sh ./.scripts/travis_script.sh
