/*
Project Euler Problem 2

This is a port of the optimized version found in python. For a proof of why this
works, see that implementation

Problem:

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/
pub fn p0002() -> i128 {
    let mut answer: u64 = 0;
    let mut i = 2;
    let mut j = 8;
    while i < 4000000 {
        answer += i;
        let tmp = 4 * j + i;
        i = j;
        j = tmp;
    }
    return answer;
}
