/*
Project Euler Problem 12

I'm very glad that I did the most expansive version of my prime infrastructure
from the start.

Problem:

The sequence of triangle numbers is generated by adding the natural numbers. So
the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
*/
use crate::primes;
use crate::include::utils::Answer;

pub fn p0012() -> Answer {
    let mut num: u64 = 0;
    for x in 1.. {
        num += x;
        if primes::proper_divisors(num).len() > 500 {
            return Answer::Int(num.into());
        }
    }
    unreachable!();
}
