/**
 * Project Euler Problem 2
 * 
 * Moved the fibonacci optimization to javascript
 * 
 * Problem:
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two
 * terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 **/
exports.p0002 = function() {
// for a proof on why this formulation works, see python/p0002.py
    let answer = 0;
    let i = 2;
    let j = 8;
    let tmp = 0;
    while (i < 4000000) {
        answer += i;
        tmp = 4 * j + i;
        i = j;
        j = tmp;
    }
    return answer;
};
