/*
Project Euler Problem 2

More iterator usage

Problem:

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

#include <stdio.h>
#include "include/fibonacci.h"

#ifdef DOXYGEN
namespace c::p0002 {
#endif

int main(int argc, char const *argv[])  {
    unsigned long long answer = 0;
    fibonacci fib = fibonacci1(3999999);
    while (!fib.exhausted)   {
        next(fib);  // odd (1, 3, 13, 55, ...)
        next(fib);  // odd (1, 5, 21, 89, ...)
        answer += next(fib);  // even (2, 8, 34, 144, ...)
    }
    printf("%llu\n", answer);
    return 0;
}

#ifdef DOXYGEN
}
#endif
