/*
Project Euler Problem 12



Problem:

The sequence of triangle numbers is generated by adding the natural numbers. So
the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
*/
#ifndef EULER_P0012
#define EULER_P0012
#include <stdio.h>
#include "include/factors.h"

unsigned long long p0012() {
    unsigned long long current = 1;
    unsigned int i = 2;
    while (true)    {
        current += i;  // 3, 21, ...
        ++i;
        current += i;  // 6, 28, ...
        if (proper_divisor_count(current) > 500)
            return current;
        ++i;
        current += i;  // 10, 36, ...
        if (proper_divisor_count(current) > 500)
            return current;
        ++i;
        current += i;  // 15, 45, ...
        ++i;
    }
    return -1;
}

#ifndef UNITY_END
int main(int argc, char const *argv[])  {
    unsigned long long answer = p0012();
    printf("%llu", answer);
    return 0;
}
#endif
#endif
