/*
Project Euler Problem 44

Problem:

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = ``|Pk − Pj|``
is minimised; what is the value of D?
*/
use std::cmp::min;

use crate::include::math::pentagonal;
use crate::include::utils::Answer;


fn is_pentagonal(x: i64) -> bool {
    let root = ((24 * x + 1) as f64).sqrt();
    if root != root.round() {
        return false;
    }
    return (1.0 + root) % 6.0 == 0.0;
}

pub fn p0044() -> Answer {
    let mut d: i64 = 1_000_000_000_000;
    let pentagonals = (1..2_500).map(pentagonal).collect::<Vec<i64>>();
    for (idx, &k) in pentagonals.iter().enumerate() {
        for &j in &pentagonals[..idx] {
            if is_pentagonal(j + k) && is_pentagonal(k - j) {
                d = min(d, (k - j).abs());
            }
        }
    }
    return Answer::Int(d.into());
}
