"""
Project Euler Problem 45

Problem:

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	      	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""


def T(n: int) -> int:
    return n * (n + 1) // 2


def P(n: int) -> int:
    return n * (3 * n - 1) // 2


def H(n: int) -> int:
    return n * (2 * n - 1)


def main() -> int:
    T_idx = 286
    P_idx = 166
    H_idx = 144
    T_val = T(T_idx)
    P_val = P(P_idx)
    H_val = H(H_idx)
    while not (T_val == P_val == H_val):
        # print(P_val, T_val, H_val)
        while T_val < P_val or T_val < H_val:
            T_idx += 1
            T_val = T(T_idx)
        while P_val < T_val or P_val < H_val:
            P_idx += 1
            P_val = P(P_idx)
        while H_val < P_val or H_val < T_val:
            H_idx += 1
            H_val = H(H_idx)
    return T_val


if __name__ == '__main__':
    print(main())
