name: "C++ Lint"

on:
  push:
    paths:
      - 'cplusplus/**'
      - '!cplusplus/README.rst'
  schedule:
  - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cpp-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup clang-tidy
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: clang-tidy
        version: 1.0

    - name: Run tests
      run: make cp_lint
