name: C#

on:
  push:
  schedule:
  - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  csharp:
    strategy:
      fail-fast: false
      matrix:
        net_version: [2, 3, 5, 6, 7, 8, 9]
        os: [ubuntu-latest]
        include:
        - net_version: 6
          os: macos-latest
        - net_version: 6
          os: macos-13
        - net_version: 6
          os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET ${{ matrix.net_version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.net_version }}
        cache: true
        cache-dependency-path: 'csharp/*/packages.lock.json'

    - name: Dependencies
      run: make cs_dependencies

    - name: Run Tests
      run: |
        make cs_test COV=true
        mv csharp/Euler.Tests/TestResults/*/coverage.cobertura.xml ./

#    - name: Setup upterm session
#      uses: lhotari/action-upterm@v1
#      with:
#        wait-timeout-minutes: 5
#        limit-access-to-actor: true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  csharp-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
        cache: true
        cache-dependency-path: 'csharp/*/packages.lock.json'

    - name: Run Linter
      run: make cs_lint

