name: Fortran

on:
  push:
    paths:
      - 'fortran/**'
      - '!fortran/README.rst'
  schedule:
  - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fortran:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
        toolchain:
        - {compiler: gcc, version: 13}
        - {compiler: gcc, version: 12}
        - {compiler: gcc, version: 11}
        - {compiler: intel-classic, version: '2021.10'}
        include:
        - os: ubuntu-latest
          toolchain: {compiler: nvidia-hpc, version: '20.11'}
        - os: ubuntu-latest
          toolchain: {compiler: nvidia-hpc, version: '23.11'}
        - os: ubuntu-latest
          toolchain: {compiler: intel-classic, version: '2021.1'}
        - os: ubuntu-latest
          toolchain: {compiler: intel-classic, version: '2021.12'}
        - os: ubuntu-latest
          toolchain: {compiler: intel, version: '2024.1'}
        - os: ubuntu-latest
          toolchain: {compiler: intel, version: '2021.1'}
        - os: ubuntu-latest
          toolchain: {compiler: gcc, version: 10}
        - os: ubuntu-latest
          toolchain: {compiler: gcc, version: 9}
        exclude:
        - os: ubuntu-latest
          toolchain: {compiler: gcc, version: 13}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}

    - run: make fr_test ${{ matrix.toolchain.compiler == 'gcc' && 'COV=true' || '' }}

    - name: Upload coverage reports to Codecov
      if: ${{ matrix.toolchain.compiler == 'gcc' }}
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: Fortran
