name: Fortran

on:
  push:
    paths:
      - 'fortran/**'
      - '!fortran/README.rst'
  schedule:
  - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fortran:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, macos-13, 'ubuntu-20.04']
        toolchain:
        - {compiler: gcc, version: 13}
        - {compiler: intel, version: '2023.2'}
        - {compiler: intel-classic, version: '2021.10'}
        - {compiler: nvidia-hpc, version: '23.11'}
        include:
        - os: ubuntu-latest
          toolchain: {compiler: gcc, version: 12}
        - os: ubuntu-latest
          toolchain: {compiler: gcc, version: 11}
        - os: ubuntu-latest
          toolchain: {compiler: gcc, version: 10}
        - os: ubuntu-latest
          toolchain: {compiler: gcc, version: 9}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}

    - run: make fr_test