name: Java

on:
  push:
    paths:
      - 'java/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version:
        - 8
        - 11
        - 13
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        distribution:
        - corretto
        - dragonwell
        - liberica
        - semeru
        - temurin
        - zulu
        os:
        - 'macos-latest'
        - 'ubuntu-latest'
        exclude:
        - distribution: dragonwell
          os: macos-latest
        - distribution: semeru
          os: macos-latest
        - version: 8
          distribution: semeru
          os: ubuntu-latest
        - version: 8
          distribution: temurin
          os: macos-latest
        - version: 11
          distribution: semeru
        - version: 13
          distribution: temurin
        - version: 13
          distribution: liberica
          os: macos-latest
        - version: 13
          distribution: dragonwell
        - version: 13
          distribution: corretto
        - version: 13
          distribution: semeru
        - version: 15
          distribution: temurin
        - version: 15
          distribution: corretto
          os: macos-latest
        - version: 15
          distribution: dragonwell
        - version: 15
          distribution: semeru
        - version: 16
          distribution: temurin
          os: macos-latest
        - version: 16
          distribution: corretto
          os: macos-latest
        - version: 16
          distribution: dragonwell
        - version: 18
          distribution: dragonwell
        - version: 19
          distribution: dragonwell
        - version: 20
          distribution: dragonwell
        include:
        - version: 9
          distribution: zulu
          os: ubuntu-latest
        - version: 23
          distribution: corretto
          os: ubuntu-latest
        - version: 22
          distribution: corretto
          os: ubuntu-latest
        - version: 21
          distribution: microsoft
          os: ubuntu-latest
        - version: 17
          distribution: microsoft
          os: ubuntu-latest
        - version: 16
          distribution: microsoft
          os: ubuntu-latest
        - version: 11
          distribution: microsoft
          os: ubuntu-latest
        - version: 21
          distribution: oracle
          os: ubuntu-latest
        - version: 20
          distribution: oracle
          os: ubuntu-latest
        - version: 19
          distribution: oracle
          os: ubuntu-latest
        - version: 18
          distribution: oracle
          os: ubuntu-latest
        - version: 17
          distribution: oracle
          os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.version }}
        distribution: ${{ matrix.distribution }}
        cache: maven
        cache-dependency-path: "java/pom.xml"

    - name: Run tests (serially)
      if: ${{ matrix.version == 21 && matrix.os == 'ubuntu-latest' }}
      run: make ja_test

    - name: Run tests (in parallel)
      if: ${{ matrix.version != 21 || matrix.os != 'ubuntu-latest' }}
      run: make ja_test_auto IS_TARGET=false

    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: Java
