name: JS

on:
  push:

jobs:
  javascript:
    strategy:
      fail-fast: false
      matrix:
        version: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
        - os: macos-latest
          version: 12
        - os: macos-latest
          version: 13
        - os: macos-latest
          version: 14
        - os: macos-latest
          version: 15
        include:
        - os: macos-13
          version: 12
        - os: macos-13
          version: 13
        - os: macos-13
          version: 14
        - os: macos-13
          version: 15
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}
        cache: 'npm'
        cache-dependency-path: 'javascript/package-lock.json'

    - name: Install dependencies
      run: make js_dependencies

    - name: Run tests (serially)
      if: ${{ matrix.version == 22 && matrix.os == 'ubuntu-latest' }}
      run: make js_test COV=true

    - name: Run tests (in parallel)
      if: ${{ !(matrix.version == 22 && matrix.os == 'ubuntu-latest') }}
      run: make js_test_auto COV=true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
