name: Lua Coverage

on:
  push:
    paths:
    - 'lua/**'
    - '!lua/README.rst'
    - '.github/workflows/lua-cov.yml'
  schedule:
  - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: brew install lua@5.4 luarocks

    - run: sudo luarocks install luacov

    - run: lua -v && make lu_test COV=true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: Lua