name: Lua

on:
  push:
    paths:
    - 'lua/**'
    - '!lua/README.rst'
  schedule:
  - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        - macos-13
        version:
        - 5.4
        - 5.3
        - 5.2
        - 5.1
        - 4.0
        - 3.2
        - 3.1
        - 3.0
        - 2.5
        - 2.4
        - 2.2
        - 2.1
        - 1.1
        - 1.0

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: ${{ matrix.version }}

    - run: make lu_test
