name: Lua

on:
  push:
    paths:
    - 'lua/**'
    - '!lua/README.rst'
  schedule:
  - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        version:
        - '5.4'
        - '5.3'
        - '5.2'
        - '5.1'
        include:
        - os: macos-latest
          version: '5.4'
        - os: macos-13
          version: '5.4'

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Install dependencies
      run: |
        if [ $RUNNER_OS = 'Linux' ]; then
          sudo apt-get update
          sudo apt-get install -y lua${{ matrix.version }} ${{ matrix.version == '5.4' && 'luarocks' || '' }}
        elif [ $RUNNER_OS = 'macOS' ]; then
          brew install lua@${{ matrix.version }} luarocks
        fi

    - run: sudo luarocks install luacov
      if: ${{ matrix.version == '5.4' }}

    - run: lua -v && make lu_test ${{ matrix.version == '5.4' && 'COV=true' || '' }}

    - run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -F Lua
      if: ${{ matrix.version == '5.4' }}
