name: Lua

on:
  push:
    paths:
    - 'lua/**'
    - '!lua/README.rst'
  schedule:
  - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-20.04
        version:
        - 5.4
        - 5.3
        - 5.2
        - 5.1
        - 4.0
        - 3.2
        - 3.1
        - 3.0
        - 2.5
        - 2.4
        - 2.2
        - 2.1
        - 1.1
        - 1.0
        include:
        - os: macos-latest
          version: 5.4
        - os: macos-13
          version: 5.4

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Install dependencies
      run: |
        if [ $RUNNER_OS = 'Linux' ]; then
          sudo apt-get update
          sudo apt-get install -y lua${{ matrix.version }}
        elif [ $RUNNER_OS = 'macOS' ]; then
          brew install lua@${{ matrix.version }}
        elif [ $RUNNER_OS = 'Windows' ]; then
          choco install lua --version ${{ matrix.version }}
        fi

    - run: make lu_test
