name: Lua

on:
  push:
    paths:
    - 'lua/**'
    - '!lua/README.rst'
  schedule:
  - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        version:
        - 5.4
        - 5.3
        - 5.2
        - 5.1
        include:
        - os: macos-latest
          version: 5.4
        - os: macos-13
          version: 5.4

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Install dependencies
      run: |
        if [ $RUNNER_OS = 'Linux' ]; then
          sudo apt-get update
          sudo apt-get install -y lua${{ matrix.version }}
        elif [ $RUNNER_OS = 'macOS' ]; then
          brew install lua@${{ matrix.version }}
          brew install luarocks
        fi

    - uses: leafo/gh-actions-luarocks@v4
      if: ${{ !contains(matrix.os, 'mac') }}
      with:
        withLuaPath: "lua"

    - run: sudo luarocks install luacov
      if: ${{ !contains(matrix.os, 'windows') }}

    - run: luarocks install luacov
      if: ${{ contains(matrix.os, 'windows') }}

    - run: make lu_test COV=true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: Lua
