name: Pages

on:
  push:
    paths:
      - 'docs/**'
      - 'javascript/**'
      - 'python/**'
      - 'README.rst'
      - '**/*.rst'
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Use Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: |
          python/requirements.txt
          c/requirements.txt
          docs/requirements.txt

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install git, linguist
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: git ruby-github-linguist
        version: docs

    - name: Build sphinx docs
      run: make docs_dependencies html

    - uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/deploy-pages@v4

