name: Pages

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: 'ubuntu-22.04'

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Use Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: |
          python/requirements.txt
          c/requirements.txt
          docs/requirements.txt

    - name: Use Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install Linguist
      run: sudo gem install github-linguist

    - name: Build sphinx docs
      run: make docs_dependencies html

    - uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html/

  deploy:
    needs: build
    runs-on: ubuntu-20.04

    permissions:
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/deploy-pages@v4

