name: Pages

on: push

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - run: sudo apt-get install -y python3-clang python3-pip libclang-dev clang

    - run: sudo dpkg -S libclang.so

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: "make html"

    - uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

