name: Pages

on: push

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
  
    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v4
      with:
        path: llvm/lib/libclang.so*
        key: llvm-17

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "17.0"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - name: Symlink libclang.so
      run: sudo ln -s ./llvm/lib/libclang.so /usr/lib/x86_64-linux-gnu/libclang-17.so

    - name: Use Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: |
          python/requirements.txt
          c/requirements.txt
          docs/requirements.txt

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: "make html"

    - uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

