name: Python-Lint

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.rst'
      - '**/README.rst'
  schedule:
  - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: |
          python/requirements.txt
          c/requirements.txt

    - name: Lint
      run: make pytest LINT=only
