name: Rs

on:
  push:
    paths:
      - rust/**
      - Makefile
      - _data/**
      - .github/workflows/rust.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - toolchain: stable
            os: macos-13
          - toolchain: stable
            os: macos-latest
          - toolchain: "1.1"
            os: ubuntu-latest
          - toolchain: "1.10"
            os: ubuntu-latest
          - toolchain: "1.20"
            os: ubuntu-latest
          - toolchain: "1.28"
            os: ubuntu-latest
          - toolchain: "1.30"
            os: ubuntu-latest
          - toolchain: "1.40"
            os: ubuntu-latest
          - toolchain: "1.50"
            os: ubuntu-latest
          - toolchain: "1.60"
            os: ubuntu-latest
          - toolchain: "1.70"
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - run: cd rust && cargo build

      - run: cd rust && cargo test
        if: ${{ matrix.toolchain != 'nightly' }}

      - run: cd rust && cargo test
        if: ${{ matrix.toolchain == 'nightly' }}
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

      - name: rust-grcov
        if: ${{ matrix.toolchain == 'nightly' }}
        run: cargo install grcov && grcov -r rust

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.toolchain == 'nightly' }}
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
